menu/urls.py
from django.urls import path
from . import views
app_name = 'menu'
urlpatterns = [
    path('', views.menu_list, name='menu_list'),
    path('menu/<int:pk>/edit/', views.edit_menu, name='menu_edit'),
    path('menu/<int:pk>/', views.menu_detail, name='menu_detail'),
    path('menu/item/<int:pk>/', views.item_detail, name='item_detail'),
    path('menu/new/', views.create_new_menu, name='menu_new'),
]

mysite/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls', namespace='menu')),
    ]

if settings.DEBUG:
    import debug_toolbar
#project wide URL
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

urlpatterns += staticfiles_urlpatterns()

menu/models.py
from django.db import models

import datetime


class Menu(models.Model):
    """
    class definition for Menu object instances and db tables

    attributes season, items, created_date,
    expiration_date to objects the values
    of attributes will be determined by
    data stored in related db tables
    """
    season = models.CharField(max_length=20)
    items = models.ManyToManyField('Item', related_name='items')
    created_date = models.DateField(
            default=datetime.date.today)
    expiration_date = models.DateField(
            blank=True, null=True)

    def __str__(self):
        return self.season


class Item(models.Model):
    """
    class definition for Item object instances and db tables

    attributes name, description, chef, created_date
    standard and ingredients to objects, the values
    of attributes will be determined by
    data stored in related db tables
    """
    name = models.CharField(max_length=200)
    description = models.TextField()
    chef = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_date = models.DateField(
            default=datetime.date.today)
    standard = models.BooleanField(default=False)
    ingredients = models.ManyToManyField('Ingredient',
                                         related_name='ingredients')

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    """
    class definition for Ingredient object instances and db tables

    attributes name will be assigned to objects, the values
    of attributes will be determined by
    data stored in related db tables
    """
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

menu/forms.py
from django import forms

from .models import Menu


class MenuForm(forms.ModelForm):

    expiration_date = forms.DateField(
        help_text='valid date formats are YYYY-MM-DD, MM/DD/YYYY, MM/DD/YY')

    def clean_season(self):
        data = self.cleaned_data['season']
        season = ['autumn', 'fall', 'winter', 'spring', 'summer']
        if data.lower() not in season[:]:
            raise forms.ValidationError('you have not entered a proper'
                                        ' season please do so')
        return data

    class Meta:
        model = Menu
        exclude = ('created_date',)

menu/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import *
from .forms import *


def menu_list(request):
    """
    logic for URL '/'

    outputs a list of menus that expiration dates are
    less than or equal to today's date pre_fetches related
    items this is stored in the variable menu and is passed
    as context to the list_all_current_menus.html template
    :param request: HTTP GET Request
    :type request: object
    :return: HTTP Response
    :rtype: object
     """

    menus = Menu.objects.filter(
        expiration_date__lte=datetime.date.today()).order_by(
        'expiration_date').prefetch_related('items')

    return render(request, 'menu/list_all_current_menus.html', {'menus': menus})


def menu_detail(request, pk):
    """
    logic for  URL '/menu/<int:pk'

    detail of menu that matches menu_id passed through URL
    items this is stored in the variable menu and is passed
    as context to the menu_detail.html template
    :param request: HTTP GET Request
    :type request: object
    :param pk: menu_id
    :type pk: int
    :return: HTTP Response
    :rtype: object
    """

    menu = Menu.objects.get(pk=pk)
    return render(request, 'menu/menu_detail.html', {'menu': menu})


def item_detail(request, pk):
    """
    logic for URL /menu/item/<int:pk>

    detail of item that matches item_id passed through URL
    this is stored in the variable item and is passed
    as context to the detail_item.html template
    :param request: HTTP GET Request
    :type request: object
    :param pk: item_id
    :type pk: int
    :return: HTTP Response
    :rtype: object
    """
    item = Item.objects.get(pk=pk)

    return render(request, 'menu/detail_item.html', {'item': item})


def create_new_menu(request):
    """
        responsible for logic for URL /menu/new/

        handles logic to create a new menu object
        this function instantiates a form object
        forms.MenuForm which is a ModelForm
        if data received by form from user is valid
        the form will save and a new Model object instance
        of Menu will be created with its attributes values defined
        within the forms fields
        :param request: HTTP POST request
        :type request: object
        :return: HTTP Response
        :rtype: object
    """

    if request.method == "POST":
        form = MenuForm(request.POST)
        if form.is_valid():
            menu = form.save(commit=False)
            menu.created_date = datetime.date.today()
            menu.save()
            return redirect('menu:menu_detail', pk=menu.pk)
    else:
        form = MenuForm()
    return render(request, 'menu/menu_edit.html', {'form': form})


def edit_menu(request, pk):
    """
        responsible for logic for URL /menu/<int:pk>/edit

        handles logic to update a  menu object
        this function instantiates a form object
        forms.MenuForm which is a ModelForm
        form is prepopulated with data from menu object
        whose id is passed through the URL
        if data received by form from user is valid
        the form will save and a new Model object instance
        of Menu will be created with its attributes values defined
        within the forms fields
        :param pk: menu_id
        :type pk: int
        :param request: HTTP POST request
        :type request: object
        :return: HTTP Response
        :rtype: object

    """
    menu = get_object_or_404(Menu, pk=pk)

    form = MenuForm(instance=menu)
    if request.method == 'POST':
        form = MenuForm(request.POST, instance=menu)
        if form.is_valid():
            menu = form.save(commit=False)
            menu.save()
            return redirect('menu:menu_detail', pk=menu.pk)
        else:
            form = MenuForm(instance=menu)
    return render(request, 'menu/menu_edit.html', {'form': form,
                                                   'menu': menu})

menu/templates/menu/detail_item.html
{% extends 'layout.html' %}

{% block content %}
    <div class="post">
        {% comment %}{% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'item_edit' pk=item.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}{% endcomment %}
        <h1>{{ item.name }}</h1>
        <p><strong>Head Chef:</strong> {{ item.chef }}</p>
        <p>{{ item.description }}</p>
        <p><strong>Ingredients: </strong>{{ item.ingredients.all|join:", " }}</p>
        {% if item.standard %}
            <p><em>This item is available year-round.</em></p>
        {% endif %}
    </div>
{% endblock %}

menu/templates/menu/item_list.html
{% extends 'layout.html' %}

{% block content %}
    {% for item in items %}
        <div>
            <h1><a href="{% url 'item_detail' pk=item.pk %}">{{ item.title }}</a></h1>
            <p>{{ item.description|linebreaks }}</p>
            <p>published: {{ item.published_date }}</p>
        </div>
    {% endfor %}
{% endblock %}

menu/templates/menu/list_all_current_menus.html
{% extends 'layout.html' %}
{% block content %}
<div class="post">

    {% for menu in menus %}

        {% if menu.expiration_date %}
            <div class="date">
                Expires on: {{ menu.expiration_date|date:'D d M Y'}}
            </div>
        {% endif %}


        <h1>
            {% if user.is_authenticated %}
                <a class="btn btn-default" href="{% url 'menu:menu_edit' pk=menu.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
            {% endif %}
            <a href="{% url 'menu:menu_detail' pk=menu.pk %}">{{menu.season}}</a>
        </h1>
        <p>{{ menu.items.all|join:", "}}</p>
    {% endfor %}
</div>
{% endblock %}

menu/templates/menu/menu_detail.html
{% extends 'layout.html' %}

{% block content %}
    <div class="post">
        <h1>
            {% if user.is_authenticated %}
                <a class="btn btn-default" href="{% url 'menu:menu_edit' pk=menu.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
            {% endif %}
            {{ menu.season }}
        </h1>
        <h2>On the menu this season:</h2>
        <ul>
            {% for item in menu.items.all %}
                <li><a href="{% url 'menu:item_detail' pk=item.pk %}">{{ item }}</a></li>
            {% endfor %}
        </ul>
        {% if menu.expiration_date %}
            <div class="date">
                Menu expires on {{ menu.expiration_date|date:"F j, Y" }}
            </div>
        {% endif %}
    </div>
{% endblock %}

menu/templates/menu/menu_edit.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Change menu</h1>
    <form method="POST" class="menu-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Soda Fountain</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"></head>
<body>

    <div class="page-header">

        {% if user.is_authenticated %}
            <a href="{% url 'menu:menu_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% endif %}

        <h1><a href="{% url 'menu:menu_list' %}">Soda Fountain</a></h1>
    </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">

                {% block content %}
                {% endblock %}

            </div>
        </div>
    </div>

</body>
</html>